### ISSUE TITLE
Parsing raw wikidata objects error

### ISSUE THREAD

**Issue by arthur-kislitsin** [kachkaev/tooling-for-how-old-is-this-house#23]
While working with Krasnodar 

![image](https://user-images.githubusercontent.com/87503379/144434471-1e681a33-699f-4521-a61b-00c9abcd2208.png)

**Comment by kachkaev** [comment]
Commands should no longer crash if there are mistakes in `territory-config.yml` → `addressHandling` → `wordReplacements`. New output:

```
territory-config.yml → addressHandling: Skipping word replacement {"from":null,"to":"xxx"}
(expected "from" to be a string or an array of strings)
```
