### ISSUE TITLE
unable find region for relation

### ISSUE THREAD

**Issue by workdao** [kachkaev/tooling-for-how-old-is-this-house#4]
![Снимок экрана от 2021-04-30 12-38-42](https://user-images.githubusercontent.com/9883178/116665396-2af6f580-a9b3-11eb-8569-66d556eb9a7d.png)

**Comment by kachkaev** [comment]
Closed in 1b8504fd609552a4d7e22e8064ba8ca48d464e76 and 7d21295f3ce1990bb879a1a2020b9c84506b747c
